### ISSUE TITLE
Cultivating new coaches

### ISSUE THREAD

**Issue by saljuama** [codebar/barcelona#100]
## Description  (Updated)

Given that across all Codebar, there is always a shortage of coaches, we want to do an open talk about coaching, that could be recorded and reused to promote coaching, share the benefits, and some tips and tricks for effective coaching. 

## Scope

- [ ] Prepare a presentation about coaching 
- [ ] Discuss with Kimberly next steps
- [ ] Find out if there are people interested in sharing their coaching experiences

**Comment by KimberleyCook** [comment]
I will be opening up RSVP for this event tomorrow, https://codebar.io/events/virtual-open-day-2 a good opportunity for anyone interested in coaching to come along and ask questions. Or students who want to attend and have questions too.

**Comment by saljuama** [comment]
To make it about making a talk / training, and open it up to all codebar chapters, virtual open day for example

**Comment by Klarala13** [comment]
We discuss the idea of supporting coaches by sharing a presentation about "what is coaching" and the benefits from it and having a physical workshop. 
Also the idea of "shadowing" and generating a safer space. 
@saljuama will get information and putting it down information when he wants/can/has time.

**Comment by Bozena611** [comment]
no updates this month, and that's cool :-)

**Comment by daverick** [comment]
no updates this month, and that's cool :-)

**Comment by Klarala13** [comment]
@saljuama and @Klarala13 did a video that @KimberleyCook organized to promote coaching. 
@daverick thinsk that maybe in BCNSoftwareCrafters it might be a good place to find new coaches. 
Aaron stated coaching and he is ROCKING IT! 
@saljuama will get information and putting it down information when he wants/can/has time and or energy.

**Comment by amaliacardenas** [comment]
Here is a video that people can share to see if other people want to join as coaches. https://www.youtube.com/watch?v=YXDro52s-jU&ab_channel=codebar

Other than this there are no new updates.

**Comment by Klarala13** [comment]
We have been having some new coaches at the workshops and that´s good news. 
@Klarala13 will post on instagram a part of the video that @KimberleyCook did and make some noise as well and see if that helps to cultivate even more new coaches.

**Comment by Bozena611** [comment]
No updates for this month.

**Comment by ancagabriela** [comment]
No updates for this month and it's good, we will see better when we get to in-person workshops

**Comment by Klarala13** [comment]
No updates for this month and it's good, we will see better when we get to in-person workshops

**Comment by colmanfranco** [comment]
Franco had the idea to start making videos of coaches on every workshop that we do so then we can start sharing them on social media and promote codebar so we can get more coaches. Also, we want to talk with new hosts before a workshop so we can share experiences, what is codebar so we can motivate for more coaches to join.

**Comment by ancagabriela** [comment]
@Klarala13 tried but nobody wanted to be filmed, so she stopped. @saljuama will get some videos we already have

**Comment by saljuama** [comment]
https://youtu.be/YXDro52s-jU

**Comment by ancagabriela** [comment]
@amaliacardenas will also help
