### ISSUE TITLE
Occasional Workshop for beginners only

### ISSUE THREAD

**Issue by Bozena611** [codebar/barcelona#101]
### Description

Lately we have had a lot of advanced students in the workshops and not so many beginners. Maybe we could sometimes organize a workshop for beginners only, where current advanced students could also practice being a coach (could go well with   [Salva's idea](https://github.com/codebar/barcelona/issues/100) of cultivating coaches.

## Scope

- [ ] Discuss how we would do this without disturbing the current workshop flow
- [ ] Find a way to get new students to join
- [ ] Encourage some of our current students to practice coaching

## Some ideas

* Possibly connect with Migracode or Code Your Future free Bootcamps for newbie coaches

**Comment by KimberleyCook** [comment]
Just before Christmas we ran an Intro to HTML and CSS workshop, I could ask Kim and Shannon if they'd like to run this again?

**Comment by Bozena611** [comment]
It doesn't have to be necessarily targeted at a specific language, I thought like any other codebar workshop but students would all be beginners (in Python, JS, Java, React, SQL) so we could have a range of beginner students and a range of newbie coaches who could practice what they have learned.

**Comment by KimberleyCook** [comment]
Oh nice, sounds like a great idea! I'd be happy to help in any way to ensure it happens :)

**Comment by saljuama** [comment]
This is no longer relevant since we lost so many people and workshops no longer have 30-40 people :( so closing it
