### ISSUE TITLE
BCN SoftwareCrafters in October

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#102]
## Description 

[https://softwarecrafters.barcelona](https://softwarecrafters.barcelona) is organising their conference in October. 
they would like to collaborate with us. speaker de codebar o mas.

## Scope

- [x] decide if we want to collaborate
- [ ] decide how
- [ ] tbd

**Comment by KimberleyCook** [comment]
I'm happy to help with this if you want to collaborate with them

**Comment by saljuama** [comment]
Let's explore what options on how to collaborate
October workshop will not be remote, will be in person

@daverick  will have a meeting with a software crafters person (@immavalls) and kickstart the conversation

**Comment by Bozena611** [comment]
no update yet, as soon as there's more info David will update.

**Comment by daverick** [comment]
I had a meeting with @immavalls today.
They are proposing a few free tickets for the conference for our student. 
We might be able to make a workshop physically for 5 students there ( but some doubts and it will depend of the epidemic conditions at that time).
We could promote being a codebar coach at their assistants ( it is another motivation for https://github.com/codebar/barcelona/issues/100 )
and last but not least we could remind our coaches that if they are part of an underrepresented group they could have diversity ticket cheaper that the regular one and available as the regular ones have been historically  sold out in a few minutes.

**Comment by immavalls** [comment]
Thanks David! 
Just a note on diversity tickets: they are not cheaper, same price. The good thing is that they don't get sold out in minutes, so they are easier to get. We have diversity tickets available usually up until the event (1-2 weeks before the date).
And let's hope the situation changes a bit and we can do an in-person workshop. At the moment we don't see it, but we'll reevaluate in September if the situation is better with covid 🤞

**Comment by daverick** [comment]
I will make some announcement in the slack and get the list of students that are interested.
and mention the Diversity tickets available for coaches or student that can afford it.

**Comment by immavalls** [comment]
Thanks @daverick We still have diversity tickets on sale, the regular ones sold out quickly. For students I expect we might be able to give at least 2 free tickets.

**Comment by Klarala13** [comment]
On the slack channel we haven´t had any interest. @daverick contacted @loriking and she is interested in the ticket. 
He is also taking the opportunity to present Codebar and promote it a bit and maybe cultivate new coaches.

**Comment by immavalls** [comment]
Thanks! Hopefully next year we can do a codebar workshop in the event. And this year if we present codebar at the opening we should also get some folks interested 😄
