### ISSUE TITLE
Schedule Q3 and Q4 workshops

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#103]
## Description 

Schedule Q3 and Q4 workshops

## Scope

- [x] Schedule Q3 and Q4 workshops
- [ ] prepare for onsite ?

**Comment by saljuama** [comment]
start proposing the dates
think about holidays and which dates do we want to pause holidays @daverick , @amaliacardenas , @Bozena611 , @ancagabriela , @Klarala13 , @stefi23 , @saljuama 

dates to review on next monthly

**Comment by Bozena611** [comment]
We are taking a break in July and August, @daverick is going to prepare the schedule while the rest of us are at the beach ;-)

**Comment by daverick** [comment]
They are scheduled till the end of November.
will se later if we can go back on site. 🍕 🍻

**Comment by Klarala13** [comment]
@daverick will put all of his energy into going back to in person and let´s see if we can manage for November.
