### ISSUE TITLE
anna/git

### ISSUE THREAD

**Issue by Bozena611** [codebar/barcelona#109]

**Comment by Bozena611** [comment]
The first steps in Git book, Anna asked if she can ask our students to test the book. We would like to ask her to do a Git workshop at some point.

**Comment by Klarala13** [comment]
No news this month and that´s ok :)

**Comment by amaliacardenas** [comment]
@adritek will contact Anna to see when would be a good time for her to give a git workshop and get the ball rolling. We can try to see if she is available to give the workshop either in late September or early October.

**Comment by Klarala13** [comment]
No updates for this moonth we will check again in september

**Comment by colmanfranco** [comment]
We are still waiting for the book to be finished

**Comment by daverick** [comment]
@amaliacardenas will contact Anna.

**Comment by ancagabriela** [comment]
@amaliacardenas will contact Anna.
