### ISSUE TITLE
LGTBQ+ Workshop

### ISSUE THREAD

**Issue by colmanfranco** [codebar/barcelona#113]

**Comment by Klarala13** [comment]
The idea is to get in touch with different collectives and propose a one-off workshop for march 31st, the day of Trans visibility. 
@Klarala13 will get in touch with a couple of associations and maybe it would be a good idea to have a flyer made so we can drop it off in some companies and associations during the next workshops/months.

**Comment by ancagabriela** [comment]
We do see value in this initiative so we want to do it. @Klarala13 got another lead and @amaliacardenas too. Also, we will mention this in our workshops that the code of conduct is about respecting everyone, no matter their gender, race, or religion...
