### ISSUE TITLE
review the process documentation and trello board

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#115]
* Review the [doc](https://github.com/codebar/barcelona/blob/master/processes/workshops-preparation/preparing-a-workshop.md) and the [trello board](https://trello.com/b/ccJETYgH/codebario-barcelona-workshops-planning) by a 'newbie' and update it if needed.

**Comment by ancagabriela** [comment]
@amaliacardenas and @Bozena611 will onboard Frida, Franco, and Adrian using these documents.

**Comment by ancagabriela** [comment]
Franco and Adrian received it from Kimberley. @Bozena611 will have a look and see what can she do with Frida.

**Comment by colmanfranco** [comment]
nothing happened so far. We can check next meeting

**Comment by Klarala13** [comment]
No news for now.

**Comment by Klarala13** [comment]
@fridavbg will review it with Ross since he offered to help as an organizer. That way, we kill two stones in one throw.

**Comment by Klarala13** [comment]
No updates on this yet, but with the process we will have to have for newcomers hopefully we can review the document and update it if need be.

**Comment by saljuama** [comment]
Pending review of the documents with Nils and Ros, we need a volunteer, but we are lacking some time and availability, it will happen soon (TM)

**Comment by nilsbu** [comment]
https://github.com/codebar/barcelona/pull/121

**Comment by ancagabriela** [comment]
it has been done/review/updated, if something else comes up we can create another one
