### ISSUE TITLE
Theory of Change workshop - Thoughtworks Online

### ISSUE THREAD

**Issue by Bozena611** [codebar/barcelona#119]
I’m reaching out to you because we want to setup a Theory of Change workshop within the company and would like to have some representatives of the Social Change organizations we work with. We would be pleased if someone from the Codebar organization would join this workshop. (The workshop will be in Spanish and remote)

The current dates we have are:

30 Junio de 14:00 a 17:00
14 Julio de 14:00 a 17:00
28 Julio de 14:00 a 17:00

We’ll only pick one date for the workshop, the one date that works for most people.

If this sounds interesting to you, please let me know who can attend (one person would be great) and which of these dates work for you.

Happy to take a quick call and explain further what the workshop entails.

Julien

**Comment by colmanfranco** [comment]
@colmanfranco is gonna reply that nobody can make it.
