### ISSUE TITLE
BCN codebar role in building LGBTQIA + tech community

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#51]
**Status 2019/09 Monthly Meeting**

The pride month event at Typeform was a success ( #33) in the way that we succeed in making Codebar known to the a dozen of lgbtqia + tech organization and these organizations have seen that some synergies between them was possible.
We should push this forward and promote diversity in different companies and other spaces, in a collaborative manner with other organizations already doing this.

**Comment by daverick** [comment]
## Status 201910 Monthly meeting

no real advance this week. 
@daverick will do a lightning talk about codebar or its story associated with codebar at a LGBT+Tech Barcelona

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting:**
Raquel checked with the Pride organization to see how we could collaborate. We could have a stand but it may be too costly for the benefit that we could get from it. We should discuss alternatives.

Pre-pride as planned for last year seems a good option. We can make some T-Shirts. A bunch of them (maybe?) sponsored by some of our hosts?

@raquelalvear will drive this part.
