### ISSUE TITLE
Add collaborators board

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#53]
### Status 2019/04 Monthly Meeting

There was some discussion about how to add/select new organizers and how to onboard them. @amaliacardenas will document the on-boarding process and the "manual" of what is expected from an organizer. Linked to this, it was identified that there is no repository of "common emails" ( #32 )and it could be a good idea to have them. This will be part of a new initiative owned by @amaliacardenas as of next meeting.

Apart from collaborators during the workshop, it was discussed and agreed to extend by 2 people the group of organizers. We agreed that both new members must be Spanish. Before next monthly meeting we'll talk with the candidates to see if they would like to join the organizers team.

This initiative is ongoing and should be included in next month agenda.

* [x] Document it 
* [x] present it
* [x] follow-up

**Comment by daverick** [comment]
### Status 2019/05 Monthly Meeting 

No progress. @raquelalvear is interested in collaborating with this initiative.

**Comment by daverick** [comment]
### Status 2019/07 Monthly Meeting 

Owner: @saljuama & @loriking

Reminder: To track people who assist the workshops and are willing to collaborate with Codebar. The current idea is to document our process, and activities, and then be able to link potential people who can collaborate on this.

No progress

Should we consider this topic before we consider for more organisers?

**Comment by daverick** [comment]
### Status 2019/09 Monthly Meeting

No progress - now @jmbriano takes over this initiative. Tryin to plan this before considering enrolling new organisers @raquelalvear will see if she can work with @Edu on the feedback

**Comment by jmbriano** [comment]
Status: pull request created a week ago. No comments made. I suggest 1 more week for comments, then merge. After, announce on Slack when merged

**Comment by daverick** [comment]
Status 2019/10 Monthly Meeting

todo validar la PR.

mañana martin lo presenta en ubiqum

algunas correction ortográfica.

**Comment by jmbriano** [comment]
In yesterday workshop we had our first official collaborator as _door person_. There was a second collaborator to be the _MC_ but that person finally could not make it to the workshop.
I believe there is nothing pending except for following up in a few months. 

(Not sure if I should move it to "close" or stays here for the "follow up". Maybe a new column?)

**Comment by amaliacardenas** [comment]
Perhaps we should add a checklist item asking the codebar community to collaborate on the trello board for each workshop. This will help us have collaborators be a regular part of codebar, rather than having people participate sporadically.

**Comment by jmbriano** [comment]
We'll announce the available rolls in Barcelona channel before each workshop and after a few workshops we'll document it in the preparing a workshop process

**Comment by daverick** [comment]
Create a task to revisit this monthly.

**Comment by jmbriano** [comment]
Update: same as previous monthly

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting**
Pending to add in Trello template card

@jmbriano will do

**Comment by ancagabriela** [comment]
Status 202006 Monthly meeting

@amaliacardenas  will do

**Comment by amaliacardenas** [comment]
I have updated the checklist item on the trello template and pending cards. @jmbriano if you want to review the trello board we can close up this issue in our next meeting.

**Comment by jmbriano** [comment]
The bullet in the TEMPLATE cards looks OK for me :)
Thanks a lot!
