### ISSUE TITLE
Handbook for organisers

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#54]

**Comment by daverick** [comment]
## Status 201910 monthly meeting:

no advance this month but:
* there is a codebar global initiative about documentation and we should unite forces.
* we will document as we see it is needed

**Comment by amaliacardenas** [comment]
As of Nov 1st, there are no updates for this initiative.

**Comment by Bozena611** [comment]
Moving this to ongoing so we can add changes. @amaliacardenas will create a first draft for Organizer Expectations for BCN chapter.

**Comment by ancagabriela** [comment]
@ancagabriela  @Klarala13 will create the first draft for Organizer Expectations for BCN chapter.

**Comment by amaliacardenas** [comment]
no updates for now but some coming soon :p

**Comment by Klarala13** [comment]
@amaliacardenas will create a doc on github and share it with @ancagabriela and @Klarala13 so we can draft something up for september. 
We are thinking maybe it would be good to ask someone else to join as an organizer but let´s see in septmeber how we are doing ;)

**Comment by colmanfranco** [comment]
No updates for this month

**Comment by ancagabriela** [comment]
no updated neither

**Comment by Klarala13** [comment]
No updates and that´s super ok.

**Comment by ancagabriela** [comment]
no updates, that's okay

**Comment by colmanfranco** [comment]
no updates and that's fantastic

**Comment by Klarala13** [comment]
No updates for now and that´s ok

**Comment by saljuama** [comment]
Closed because we will do in another topic that is on going abour reviewing documentation and update if needed https://github.com/codebar/barcelona/issues/115
