### ISSUE TITLE
Social Media Fun (Instagram, Community Manager, Designer)

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#55]
### Status 2019/09 Monthly Meeting

No updates. We'll write a guide about all of the social media accounts and how to use them

**Comment by daverick** [comment]
- ayuda con Stefi sobre social media
- videos subir
- reunirse con Kimberly y nys chapter pasta templates y cosas asi

**Comment by saljuama** [comment]
we will address this one in https://github.com/codebar/barcelona/issues/99
