### ISSUE TITLE
Coach Kit

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#57]
### Status 2019/09 Monthly Meeting  
Approved and ongoing

a kit for coach so that they can explain to their coworker why coaching at codebar is super cool (came from a chat with Alyssa from typeform to how to foment their employee to coach at codebar when it will be at typeform)

Consider presenting codebar at the host company beforehand, so they can get to know what is it like to be a coach. Other ideas:

- [ ] Take a look at FAQ and the assets and use it for our future coaches
- [ ] Make videos with coaches explaining how they do it
- [ ] Talk to Kimberley!

**Comment by daverick** [comment]
3 patas:
- presentation/ lightning talks 
- documentar para facilitar la 'entrada' de los coaches
- videos experiencias

**Comment by amaliacardenas** [comment]
As of Nov 1st, there are not any updates for this initiative.

**Comment by amaliacardenas** [comment]
We will use the extra footage from Elastic to create a few videos. I am waiting to get the raw footage from David.

**Comment by daverick** [comment]
### Status 2020/01 Monthly Meeting:
@amaliacardenas and myself have the raw footages , a few TB ;-)

**Comment by amaliacardenas** [comment]
1. What is a workshop like
2. The motivation coaches to participate
3. Why is it good for a company to host and encourage employee involvement

**Comment by amaliacardenas** [comment]
I was not able to make progress on this initiative. Moving to paused for the moment.

**Comment by saljuama** [comment]
we will address this one in https://github.com/codebar/barcelona/issues/100
