### ISSUE TITLE
Publicity talk at the smart cities conference

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#59]
### Status 2019/09 Monthly Meeting

Thais is helping organize the smart cities coference and she wants to give passes to our community and promote organizations like ours (19-21 of November) She's working with decidem. They're trying to make feedback on the democratic process more transparent They want to work with the RGSOC program

**Comment by daverick** [comment]
19 de noviembre 16h-18h00

Raquel & martin trabajar presentación

**Comment by raquelalvear** [comment]
Can we have the website link to this event? 
What is the **actual** topic of this talk?
TBD: 
lightning talk OR codebar presentation?
This presentation could be used for other forthcoming events
IDEA:
- [ ] What is codebar 
- [ ] What have we achieved
- [ ] What are our short-term/long-term goals
- [ ] What can YOU do to help

**Comment by amaliacardenas** [comment]
Hi @raquelalvear and @jmbriano 
To sign up for the event and obtain your tickets to the smart city conference, you have to sign up using this form https://forms.gle/dtt3nzsyiF9a2r8w6

The topic of the talk can either be presenting codebar, or a lightning talk that addresses gender and inclusion in tech. You have approximately 10 minutes that can be divided into 5 minute presentation and 5 minute Q&A. The full program for for the sharing cities action stand lab can be found here: http://bit.ly/2Vuz2Tp

**Comment by amaliacardenas** [comment]
Raquel has signed up to present the codebar at the Smart Cities conference. Amalia sent her the codebar presentation that David prepared as a guide.
