### ISSUE TITLE
New organizers

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#60]
### Status 2019/07 Monthly Meeting 

Do we need more organizers? Stefi shown interest. How many do we need? Minimum req is to be able to attend montly meetings. Propose names for potential organizers

**Comment by daverick** [comment]
### Status 2019/09 Monthly Meeting

Not to be discussed until we have the collaborators board #53

**Comment by jmbriano** [comment]
Someone came to me interested about this. I'd like to reopen this topic cc @loriking for this Thursday

**Comment by amaliacardenas** [comment]
@amaliacardenas will take care of onboarding all

**Comment by amaliacardenas** [comment]
I was not able to schedule an onboarding session with Steffi and Anca. But I did add them to Facebook, Meetup, Twitter, Slack, Trello and asked the London organizers to grant them access to the tools we use.

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting**
This will be done in between the workshops. Anca knowns majority of the tools already and Stefi will not be available until summer.

**Comment by daverick** [comment]
Still waiting to onboard @ancagabriela and Steffi.

**Comment by loriking** [comment]
@daverick to follow-up with @stefi23 about her onboarding
