### ISSUE TITLE
Pride Month 🌈

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#63]
### Status 2019/03 Monthly Meeting

Over the summer we were approached by a host regarding a sponsorship for participating at the bcn gay pride.

The host will be contacted to better understand their intention.

**Comment by daverick** [comment]
### Status 2019/04 Monthly Meeting
No progress from previous meeting. @loriking will set up a meeting with Miquel

**Comment by daverick** [comment]
### Status 2019/05 Monthly Meeting
No progress. @saljuama will put @daverick in contact with TW people from OutWorks so this initiative can be pushed forward.

**Comment by daverick** [comment]
### Status 2019/06 Monthly Meeting

The idea is to bring together different collectives from various companies and organize a social event. @daverick , @raquelalvear  and @amaliacardenas  will work together on this initiative. We will contact several people from Thoughtworks and Typeform to get the initiative going.

**Comment by daverick** [comment]
#33

**Comment by daverick** [comment]
### Status 2019/07 Monthly Meeting

It's over T_T

Event went really well, and had a good traction.

SADLY this event can be closed until next year

**Comment by raquelalvear** [comment]
Reopening this issue to talk about our possible plans for Pride 2020 and maybe create a team to work on this. Possibilities for now:
- Just like last year: Gathering of companies that share a diversity goal
- Participation in the pride parade: as a group of volunteers or perhaps something else

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting**
This is about a gathering different groups focused in LGBTQI+ next to the pride date.

There was a meeting between last week to discuss about how to organise it. 

David will set up an online way of communication so it can progress faster. 

@daverick is driving

**Comment by daverick** [comment]
## Status 202004 Monthly meeting

a specific slack space has been created.
But the energy to got forward is not there.
