### ISSUE TITLE
Track initiatives for the monthly meeting 

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#64]
### Status 2019/07 Monthly Meeting

Do we consider a Trello board to manage the initiatives? @loriking offers to create it This can be used to share how we work for promotional purposes!

---
- [x] prepare a GitHub project with the current initiatives
- [x] use it for October meeting
- [x] agree on its usage
- [x] document 
- [x] Review the meeting rescheduling process

**Comment by daverick** [comment]
### Status 2019/08 Monthly Meeting

We'll have the monthly meetings in a project on github from now on [here](../projects/2)

**Comment by daverick** [comment]
Hi @codebar/barcelona!

I have moved the list of initiatives to this [project](../projects/2). I have recollected the items form last meeting and created issues or reused issues or PR for each initiatives. I have added in some the status of each monthly meeting in it.

I have set up the assignees, feel free to add/remove yourself and add some comments or references in the issues.

I will present it to you at the next meeting and if you agree I will document it ;-)

- [x] prepare a GitHub project with the current initiative
- [ ] use it for October meeting
- [ ] agree on its usage
- [ ] document

**Comment by daverick** [comment]
## Status 2019/10 Monthly Meeting:

How the project [Initiatives - Monthly Meetings](../projects/2) is configured and should be used has been presented and used during the meeting.
Looks like it will easier to manage than the previous process with the document for each meeting.
Even if we have lost the possibility of everybody to /lgtm the report.
Next step is to document it.

**Comment by jmbriano** [comment]
Maybe we can experiment with everyone updating the initiatives owned prior to the meeting. And during the meeting present that update and gather feedback (which can be added as an edit or as a subsequent comment)

**Comment by daverick** [comment]
I had the same idea, it should make the process better and give less work to the meeting owner.
Let’s propose it to the next meeting? If anybody want to try it we can compare.


Enviat des del meu iPad

El 6 oct 2019, a les 21:17, jmbriano <notifications@github.com> va escriure:

**Comment by jmbriano** [comment]
David, can you add to this card the following task:
- "Review the meeting rescheduling process".

It seems to me that we are losing a lot of energy on this. I believe we should go back back to the threshold (i.e: define a minimum quorum, if that is met then no reschedule).

As this card consists on updating this process i think we could squeeze this in

**Comment by daverick** [comment]
## Status 2019/11 Monthly Meeting:

- adding a new task: Review the meeting rescheduling process as the current process for scheduling is not working that well for the organiser and for the attendant to maintain their agenda.
- propose that each of owner update its initiative with what has happened in the previous mouth (example: :this:).

**Comment by daverick** [comment]
## Status 2019/12 Monthly Meeting:

no advance

**Comment by daverick** [comment]
Needs documentation and them close out

**Comment by daverick** [comment]
Proposed documentation in the PR #74

**Comment by daverick** [comment]
## Status 2020/01 Monthly Meeting:

New documentation is waiting for approval in the PR #74

**Comment by daverick** [comment]
## Status 2020/02 Monthly Meeting:

Document has been approved and merged.

now the debate os about the meeting rescheduling process!

**Comment by raquelalvear** [comment]
If half of us are present, we're OK with the meeting. If more than half can't make it, the facilitator of the meeting should propose another date

**Comment by jmbriano** [comment]
**Status 2020/03 Monthly Meeting:**
Documentation is waiting for approval in the PR #74

**Comment by daverick** [comment]
#74 approved and merged. closing!
