### ISSUE TITLE
2020 Workshops Calendar

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#66]
We should start scheduling the first 2020 workshops 2020 soon.
We should list out priorities and objectives and limitations, validate them so that afterwards it issue needed to execute.
We have the prioritization criteria #22, some engagements with some host but maybe it is not necessary to schedule all year long now and give us more freedom along the year.

**Comment by raquelalvear** [comment]
TBD:
How many workshops per month? how many of them are regular and how many one-offs?
should we have one regular every other Thursday if we're also having a one-off? If so, when should the one-off be placed?
Can we make a common calendar with other similar organizations so we don't overlap each other?
Proposal from David: only work with the first 6 months of the year for now

**Comment by daverick** [comment]
* 2 normal workshops per month looks good to me as long as the one-off and other activities are added to this normal schedule. maybe we could try to add one more when we have more assistance and coaches and take out when we have so much less it is dificultades to have a correct student/coach ratio?
* Try other days in the week is a good idea. I would rather test it by moving the standard workshop and let the one-off on Thursday as our community is used too.
* We could list the other organisations complementary to us and have contact with them, indicating we would like to have compatible calendar, pre annonce our schedule to them, then validate it if no conflict and publish to them to. maybe a shared google calendar could be useful.
* furthermore we should gather the wish of our host for how many/when they want to host, maybe let some room for a possible new host ( one by trimester?)

**Comment by raquelalvear** [comment]
My proposal:
Start with January 16th and plan from then every other Thursday for the regular workshops.
If we start programming them now, we could move these days to fit a one-off if need be.
I'll add these days to the calendar in trello and wait for your **OK**.

**Comment by raquelalvear** [comment]
We decided to start presenting ourselves at 18:45 so we can start coding at 19:00

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting**
@jmbriano will drive the pending documentation with @raquelalvear 
Doc: rotation tool, how to defined dates, how often.
