### ISSUE TITLE
Organize a organizer retrospective

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#75]

**Comment by jmbriano** [comment]
**Status 202003 Monthly meeting**
No update

**Comment by loriking** [comment]
@loriking send doodle for time/date

**Comment by ancagabriela** [comment]
@saljuama asks Monica to facilitate the retro
@ancagabriela send doodle end of June

**Comment by daverick** [comment]
new retro schedule on then 4th of September
Organizers should free their agenda.
If some organizer cannot join, the retro will go forward anyway.
as it will be surely onlines, the result can be consulted and commented by the organizer that won't be able to attend.
