### ISSUE TITLE
Virtual Workshops ?

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#77]

**Comment by daverick** [comment]
The test go well, but few coaches.
energy to do it?
ask the community of coaches?

**Comment by loriking** [comment]
@amaliacardenas to ask students if they are interested in coaching
@loriking to see about `beach` coaches
@ancagabriela  & @raquelalvear to email students and coaches 
@ancagabriela will post in coaches and organizers channels for more coaches

**Comment by ancagabriela** [comment]
@ancagabriela organize another workshop end of June, 25th. Send the document we have to organizers, correct it and adjust to new settings

**Comment by daverick** [comment]
@saljuama & @amaliacardenas would like to organize one next week 9th or the following 16th.

**Comment by amaliacardenas** [comment]
Zoom worked well as a tool. Zoom has an option to have a free version for charities. We need to bring this option up with Kimberly. @saljuama will contact Kimberly to see if we can get an independent license. 

Attendance was a problem: we decided to send personalized emails to people the day before the workshop. Attendance needs to be confirmed by participants. 

@loriking will send the workshop emails the day before the workshops.

**Comment by jmbriano** [comment]
**Update 2020.11.06:**
Salva discussed with Kimberly, there is a Codebar Zoom account, but it does not have breakout rooms. 
We can use current account for now. 
On emails: there were more early cancellations, which allowed us to pull people from the waiting list, nevertheless, there is still people no-showing which makes pairing challenging.
Next workshop is on 12th/November
@amaliacardenas  will contact the people that did not show up to see if it was a technical problem to find the right place to join

**Comment by KimberleyCook** [comment]
I'm not sure how much you've used the attendance email feature for students but, on the admin area of a students profile there is a no show attendance email. Some chapters were hesitant to use. but since they have started they've have seen an improvement in no shows.

**Comment by loriking** [comment]
Closing issue as we're continuing with workshops and will send the automatic emails through the webpage
