### ISSUE TITLE
Collaboration with Migracode

### ISSUE THREAD

**Issue by amaliacardenas** [codebar/barcelona#80]
Amalia met with Vincent Van Grondelle from Migracode to discuss possible ways to collaborate. The meeting was mostly to get to know each other. We discussed hosting joint events, but since codebar's events are virtual at the moment, we will hold off on co-hosting until a future date. 

We spoke about either having a lightning talk at the beginning of a virtual codebar or hosting a separate webinar/conference on the strength of open education. Speakers could be a Migracode representative, CodeBar representative, volunteers who worked both at Migracode and CodeBar would be a plus.

**Comment by jmbriano** [comment]
**Update 2020.11.06:**
Amalia met Migracode and LearnByDoing and Hironhack. 
@amaliacardenas will share the info in Barcelona and global channels. 
Timeline for the project is challenging but we would like to support the initiative. Do they have a CodeOfConduct?

**Comment by loriking** [comment]
Pilot ends on 10 December. Good results. 
Point coaches to migracode slack channel @amaliacardenas

**Comment by amaliacardenas** [comment]
The pilot ended and we were very proud of what the students were able to accomplish in 10 days. We had some organizational hiccups, but overall we were happy with the results. Migracode, Learn by Helping and Codebar had a meeting and noted ways we can improve on future sessions. For now, the students uploaded what they were able to finish. In late January Learn by Helping will let us know which of the 5 projects will continue as real projects and we will see if our students want to continue helping with the development part.

We are currently discussing ways to collaborate with Migracode Women.

**Comment by saljuama** [comment]
For now, collaboration is over, in the future more possible collaborations will be assessed! 
Good job!!! \o/
