### ISSUE TITLE
Continuous Improvement

### ISSUE THREAD

**Issue by saljuama** [codebar/barcelona#81]
Original proposal in slack (will only be accessible to the members in that channel)  
https://codebar.slack.com/archives/G1U8UFP9V/p1600212648026400

Trello: https://trello.com/b/ccJETYgH/codebario-barcelona-workshops-planning

**Comment by jmbriano** [comment]
**Update 2020.11.06:**
@saljuama will update the description on this card and we can then park #75

**Comment by saljuama** [comment]
We've been trying to schedule a organisers retrospective, because we all are aware that there is room for improvement in our processes and we wanted to dedicate some time to share our thoughts, reflect together and come up with possible improvements, but we've had to postpone several times because it was hard to schedule a slot that would work for everyone. 

So here is an initial proposal to bring the space for us to reflect on what we do, find possible improvements and get better as a team. In the proposal are considered our current constraints, which is availability and time from the organisers. This process would not be something set in stone and definitely can be evolved / changed to adapt to our ways of working. 

**Pre-requisite:** 
- [x] Setup a place where we organisers can share privately their thoughts, so they can feel safe to share what its on their mind, without being worried about implications or repercussions. => Trello board

**Before the monthly meetings:** 
* Each organiser can add 1 card (or none, is not mandatory) to the improvements column. The reason it is only 1 card is to force us to prioritise the most important things first, and we can tackle them bit by bit, rather than to many at once. The focus should be on our processes as organisers, as we already have the rest of the monthly meeting to discuss about codebar itself 😄 

Before writting down a topic, remember the prime directive: 
> "Regardless of what we discover, we understand and truly believe that everyone did the best job they could, given what they knew at the time, their skills and abilities, the resources available, and the situation at hand."

This should not be used as an opportunity to blame or vent out. Some ideas to inspire you to write a topic (but not limited to): 

* We are struggling with ______ because ______
* I can't do ______ because ______
* We are successfully doing ______ but we would need more of it, because ______ 
* ______ is happening, which is impacting us  ______. 


**During the monthly meetings:** 
1.  ( up to 5 mins ) During the monthly session, we go through the list of improvements, without discussing them just yet, can ask for clarification questions to make sure it is understood. 
2. ( ~1 min )  Once all the topics are clear, we do a round of votes
3. ( up to 10 mins )Discuss the most voted item, and figure out what kind of actions we can take to improve

For the rest of the topics, each organiser can decide if to keep it as is, or to change it for the next monthly meeting.

**Comment by loriking** [comment]
Everyone will review and conversations will take place in Slack to determine next steps @daverick @amaliacardenas @jmbriano @raquelalvear @ancagabriela

**Comment by saljuama** [comment]
Process is ok for everyone
@saljuama  will update documentation for the proces sin the monthly

**Comment by raquelalvear** [comment]
no progress this month

**Comment by daverick** [comment]
@saljuama has a pending task about create template for an issue template

**Comment by amaliacardenas** [comment]
@saljuama created a template to be used when creating a new issue. To access it, you need to click on the issues link, next click on the new issue green button, and you can access the template. Once you have created the issue make sure you apply a label to it.

**Comment by amaliacardenas** [comment]
Nothing for this month under the continuous improvement column. :)

**Comment by Klarala13** [comment]
Nothing new this month in the continuous improvement column.

**Comment by Bozena611** [comment]
Nothing new this month, next month maybe, who knows ;-)

**Comment by ancagabriela** [comment]
Nothing new this month, next month maybe, who knows ;-)

**Comment by Klarala13** [comment]
Nothing new this month, next month maybe, who knows ;-)

**Comment by Klarala13** [comment]
Nothing new this month. :)

**Comment by ancagabriela** [comment]
Nothing new!

**Comment by Klarala13** [comment]
Nothing new for now :)

**Comment by ancagabriela** [comment]
nothing new

**Comment by saljuama** [comment]
Nobody never adds anything, and whenever we have something to change, we just do, so roll without it and see if this is cool
