### ISSUE TITLE
katas

### ISSUE THREAD

**Issue by loriking** [codebar/barcelona#83]
This involves having katas available for during the workshops for students who have completed the tutorials but don't have specific projects in mind. 

Can be solved using TDD or just solution first depending on comfort level of student/coaches

- [ ] Complete exercises in JavaScript, Python
- [ ] Provide coaches with example solutions
- [ ] Provide students with problem specifications

**Comment by jmbriano** [comment]
**Update 2020.11.06:**
Lori has a bunch of Katas that can be used in workshops for groups that don't know what to do in the sessions.

**Comment by loriking** [comment]
@ancagabriela and @loriking to post kata/solutions

**Comment by ancagabriela** [comment]
google drive folder for the katas
https://drive.google.com/drive/folders/1uvH6-jofBJEhk5rRMKYKxjoq08eUq60F?usp=sharing

**Comment by saljuama** [comment]
It will be ready for the next workshop
Action: experiment what is the best format in the next workshop

**Comment by raquelalvear** [comment]
@ancagabriela will take ownership of this task

**Comment by daverick** [comment]
no advance this month and that is OK!

**Comment by amaliacardenas** [comment]
@stefi23 will speak with @ancagabriela to see what progress has been made. The idea is to keep a simple repo that can be accessed by coaches during workshops.

**Comment by saljuama** [comment]
Discussion about adding it to github or drive is enough: 
@ancagabriela  to give access to the FOLDER!! for organisers
Then spread the word about the existence of the katas, in the usual channels (slack, social media, workshops announcements, etc)

**Comment by saljuama** [comment]
No updates , salva is sad because no karate emojis

**Comment by Bozena611** [comment]
klara added a new link :-) :+1:

**Comment by daverick** [comment]
no updates, and is still ok 🌟 🍏

**Comment by Klarala13** [comment]
no updates, and is still ok 🌟 🍏

**Comment by daverick** [comment]
no updates and it's OK 🌊

**Comment by amaliacardenas** [comment]
We already have a list with some Katas on there. If there is a need for more in the future, we can re-open an issue. For now, we are closing this issue.
