### ISSUE TITLE
Organize some online talk

### ISSUE THREAD

**Issue by amaliacardenas** [codebar/barcelona#84]

**Comment by amaliacardenas** [comment]
Thoughtworks could provide some funding for a speaker if need be. They can also help find speakers if we need help. Julien would be the contact person.

**Comment by jmbriano** [comment]
Update 2020.11.06: 
Funding discussions on-going. 
This is independent from the bi-weekly workshops. Their goal would be to strengthen the social part of Barcelona-social. 
They should not replace the regular workshops but to be on top of them (so it would mean 3+ meetings per month). The priority is not to loose track with the regular workshop. 
Org team capacity is a bit limited right now so we agree to park it until January
