### ISSUE TITLE
update virtual event templates in workshop planning in trello

### ISSUE THREAD

**Issue by daverick** [codebar/barcelona#92]
* adapt it completely to virtual event
* remove some part: Facebook? meetup? twitter?
* others?
* substitute silly question to something more IT related and empowering?

**Comment by daverick** [comment]
Initiative accepted.

**Comment by amaliacardenas** [comment]
No updates for this month. @daverick will work on cleaning up the trello board template.

**Comment by saljuama** [comment]
Maybe next month 😇

**Comment by saljuama** [comment]
Perhaps in august, we are already realistic for July 😏

**Comment by Bozena611** [comment]
David will do this while on the beach :-)

**Comment by daverick** [comment]
No updates for this month. 🔍

**Comment by Klarala13** [comment]
We want to go back to in person. We don´t want to update this. 
However, we should update the email template since it mentions Discord and not Zoom. @Bozena611 will do it.

**Comment by daverick** [comment]
no update this month and t'cool 🎄

**Comment by amaliacardenas** [comment]
No updates for this month and that is cool. 👍

**Comment by Klarala13** [comment]
@daverick cleaned up a bit the documentation. 
We don´t want to update this one anymore but we want to review the in person one. @amaliacardenas will review the template so that we don´t all go hungry on the next in person workshop.

**Comment by Bozena611** [comment]
@amaliacardenas will review the in-person template for next session.

**Comment by ancagabriela** [comment]
no updates for this month, @amaliacardenas will review the in-person template for next session.

**Comment by amaliacardenas** [comment]
I checked the templates in the Trello board for both virtual and in-person events. To keep the board clean, I removed the collaborator's checklist item. I think we have enough organizers at the moment to manage the tasks for the workshops. We can add codebar collaborator's in the future if we need more help.

**Comment by Klarala13** [comment]
@amaliacardenas reviewd it and made some changes, for example removing the collaborator checkbox. Other than that it looks good so we can close this item.
